# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Alfons Muñoz Roig
title: Cloud Engineer, Data Scientist
email: alfonsmr@gmail.com
website: www.niutech.mx

# Social links
twitter_username: alfons_mr
github_username:  alfonsmr
# dribbble_username: jekyll
# facebook_username: alfonsmr
# flickr_username: jekyll
# instagram_username: alfonsmr
linkedin_username: alfonsmr
# pinterest_username: jekyll
# youtube_username: alfonsmr
# googleplus_username: +jekyll

# About Section
about_title: Perfil
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Soy un entusiasta de la tecnología que se especializa en ayudar a las personas y hacer que las empresas funcionen mejor a través de la tecnología moderna, además de un fanático de todo lo relacionado con la electrónica y el IoT. Desde hace años he sido consultor de tecnología para pequeñas empresas, ayudándolas a preparar la transición desde una infraestructura obsoleta para el futuro con soluciones modernas en la nube y a transformar su forma de trabajar. Disfruto pasar tiempo con mi familia, practicar ciclismo y mantenerme al día con las tendencias tecnológicas modernas. 

# Projects Section
# projects_title: Projects

# Experience Section
experience_title: Experiencia

# Education Section
education_title: Educación

# More Section
more_title: Cursos
more_content: | # this will include new lines to allow paragraphs
  Otros cursos realizados:
   - [Introduction to Data Science Specialization - Coursera](https://www.coursera.org/account/accomplishments/specialization/certificate/3ZMJ8JNEHS4J)
   - [Google IT Automation with Python Specialization - Coursera](https://www.coursera.org/account/accomplishments/specialization/certificate/4VWNF724LGT9)
   - [Cloud Engineering with Google Cloud Specialization - Coursera](https://www.coursera.org/account/accomplishments/specialization/certificate/V7KMEJBYGY4E)
   - [G Suite Administration Specialization - Coursera](https://www.coursera.org/account/accomplishments/specialization/certificate/PYHA94RZUHY3)
   - [Django for Everybody Specialization - Coursera](https://www.coursera.org/account/accomplishments/specialization/certificate/ZJM8373AKVSV)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
